### ISSUE TITLE
finite_difference_gradient changes input when throwing error

### ISSUE THREAD

**Issue by amrods** [JuliaDiff/FiniteDiff.jl#111]
This throws an error
```
using FiniteDiff
sumlog(x) = sum(log(i) for i in x)
x = [1e-6, 1e-6]
FiniteDiff.finite_difference_gradient(sumlog, x)
```
but `x` is changed:
```
x
#2-element Array{Float64,1}:
# -5.05545445239334e-6
#  1.0e-6
```

**Comment by ChrisRackauckas** [comment]
This is due to the mutation in the gradient. It's the same issue as https://github.com/JuliaDiff/FiniteDiff.jl/issues/82 actually. @kanav99 since I know you're going to take a day through this library, it might be nice to clean this up as well. Essentially, in the gradient config we should just have another cache array for the perturbations.

**Comment by kanav99** [comment]
Yes having a look
