### ISSUE TITLE
Type piracy of Base.vec on Number

### ISSUE THREAD

**Issue by KristofferC** [JuliaDiff/FiniteDiff.jl#97]
I am getting precompilation warnings / erorrs from the type piracy of `Base.vec` on Number:

https://github.com/JuliaDiff/FiniteDiff.jl/blob/85daccefe21a0d9691d6c620bbdbd414c596588b/src/jacobians.jl#L127-L129

I would suggest just defining

```jl
myvec(x) = vec(x)
myvec(x::Number) = x
```

and use `myvec` in the code instead.

**Comment by ChrisRackauckas** [comment]
sure, but why not add this to Base?

**Comment by KristofferC** [comment]
Because it doesn't fit at all with what `vec` does, or?

**Comment by ChrisRackauckas** [comment]
It makes it safe for recursion and for use when you can swap in and out static arrays, so it fixes it in many contexts.

**Comment by KristofferC** [comment]
The definition here doesn't even return a vector? It seems you want something else than `Base.vec`.

**Comment by ChrisRackauckas** [comment]
numbers for a vector space, and they are the vectors in their vector space, so any algorithm that acts over a vector space works fine replacing the internal vectors with numbers by appropriately defining how to get the vector form from a number (i.e. itself). That said, this is an easier thing to just do rather than discuss, so it's probably a good thing to just pirate.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiff/FiniteDiff.jl/pull/98
